; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	D:\MyCodes\ChaosFighter\trunk\ChaosFighter\HGEGame\MyGame.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?value@?$integral_constant@_N$0A@@tr1@std@@2_NB	; std::tr1::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@tr1@std@@2_NB	; std::tr1::integral_constant<bool,1>::value
PUBLIC	?value@?$integral_constant@I$0A@@tr1@std@@2IB	; std::tr1::integral_constant<unsigned int,0>::value
PUBLIC	?_Rank@?$_Arithmetic_traits@_N@std@@2HB		; std::_Arithmetic_traits<bool>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@D@std@@2HB		; std::_Arithmetic_traits<char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@C@std@@2HB		; std::_Arithmetic_traits<signed char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@E@std@@2HB		; std::_Arithmetic_traits<unsigned char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@F@std@@2HB		; std::_Arithmetic_traits<short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@G@std@@2HB		; std::_Arithmetic_traits<unsigned short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@H@std@@2HB		; std::_Arithmetic_traits<int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@I@std@@2HB		; std::_Arithmetic_traits<unsigned int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@J@std@@2HB		; std::_Arithmetic_traits<long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@K@std@@2HB		; std::_Arithmetic_traits<unsigned long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_J@std@@2HB		; std::_Arithmetic_traits<__int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_K@std@@2HB		; std::_Arithmetic_traits<unsigned __int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@M@std@@2HB		; std::_Arithmetic_traits<float>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@N@std@@2HB		; std::_Arithmetic_traits<double>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@O@std@@2HB		; std::_Arithmetic_traits<long double>::_Rank
CONST	SEGMENT
_MeterPerPixel DD 03bc985f0r			; 0.00615
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@O@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@O@std@@2HB DD 09H		; std::_Arithmetic_traits<long double>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@N@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@N@std@@2HB DD 08H		; std::_Arithmetic_traits<double>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@M@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@M@std@@2HB DD 07H		; std::_Arithmetic_traits<float>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_K@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_K@std@@2HB DD 06H		; std::_Arithmetic_traits<unsigned __int64>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_J@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_J@std@@2HB DD 06H		; std::_Arithmetic_traits<__int64>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@K@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@K@std@@2HB DD 05H		; std::_Arithmetic_traits<unsigned long>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@J@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@J@std@@2HB DD 05H		; std::_Arithmetic_traits<long>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@I@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@I@std@@2HB DD 04H		; std::_Arithmetic_traits<unsigned int>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@H@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@H@std@@2HB DD 04H		; std::_Arithmetic_traits<int>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@G@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@G@std@@2HB DD 03H		; std::_Arithmetic_traits<unsigned short>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@F@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@F@std@@2HB DD 03H		; std::_Arithmetic_traits<short>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@E@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@E@std@@2HB DD 02H		; std::_Arithmetic_traits<unsigned char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@C@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@C@std@@2HB DD 02H		; std::_Arithmetic_traits<signed char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@D@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@D@std@@2HB DD 02H		; std::_Arithmetic_traits<char>::_Rank
CONST	ENDS
;	COMDAT ?_Rank@?$_Arithmetic_traits@_N@std@@2HB
CONST	SEGMENT
?_Rank@?$_Arithmetic_traits@_N@std@@2HB DD 01H		; std::_Arithmetic_traits<bool>::_Rank
CONST	ENDS
;	COMDAT ?value@?$integral_constant@I$0A@@tr1@std@@2IB
CONST	SEGMENT
?value@?$integral_constant@I$0A@@tr1@std@@2IB DD 00H	; std::tr1::integral_constant<unsigned int,0>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$00@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$00@tr1@std@@2_NB DB 01H	; std::tr1::integral_constant<bool,1>::value
CONST	ENDS
;	COMDAT ?value@?$integral_constant@_N$0A@@tr1@std@@2_NB
CONST	SEGMENT
?value@?$integral_constant@_N$0A@@tr1@std@@2_NB DB 00H	; std::tr1::integral_constant<bool,0>::value
CONST	ENDS
PUBLIC	??_H@YGXPAXIHP6EPAX0@Z@Z			; `vector constructor iterator'
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ??_H@YGXPAXIHP6EPAX0@Z@Z
_TEXT	SEGMENT
___t$ = 8						; size = 4
___s$ = 12						; size = 4
___n$ = 16						; size = 4
___f$ = 20						; size = 4
??_H@YGXPAXIHP6EPAX0@Z@Z PROC				; `vector constructor iterator', COMDAT
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
$LN2@vector:
	mov	eax, DWORD PTR ___n$[ebp]
	sub	eax, 1
	mov	DWORD PTR ___n$[ebp], eax
	js	SHORT $LN3@vector
	mov	esi, esp
	mov	ecx, DWORD PTR ___t$[ebp]
	call	DWORD PTR ___f$[ebp]
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	eax, DWORD PTR ___t$[ebp]
	add	eax, DWORD PTR ___s$[ebp]
	mov	DWORD PTR ___t$[ebp], eax
	jmp	SHORT $LN2@vector
$LN3@vector:
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	16					; 00000010H
??_H@YGXPAXIHP6EPAX0@Z@Z ENDP				; `vector constructor iterator'
_TEXT	ENDS
PUBLIC	??_7CMyGame@@6B@				; CMyGame::`vftable'
PUBLIC	??0CMyGame@@QAE@XZ				; CMyGame::CMyGame
PUBLIC	??_R4CMyGame@@6B@				; CMyGame::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCMyGame@@@8				; CMyGame `RTTI Type Descriptor'
PUBLIC	??_R3CMyGame@@8					; CMyGame::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CMyGame@@8					; CMyGame::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CMyGame@@8			; CMyGame::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CGame@@8				; CGame::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCGame@@@8				; CGame `RTTI Type Descriptor'
PUBLIC	??_R3CGame@@8					; CGame::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CGame@@8					; CGame::`RTTI Base Class Array'
PUBLIC	?InitGame@CMyGame@@UAE_NXZ			; CMyGame::InitGame
PUBLIC	?FrameFunc@CMyGame@@UAEXM@Z			; CMyGame::FrameFunc
PUBLIC	?RenderFunc@CMyGame@@UAEXXZ			; CMyGame::RenderFunc
PUBLIC	?Release@CMyGame@@UAEXXZ			; CMyGame::Release
EXTRN	??0CGame@@QAE@XZ:PROC				; CGame::CGame
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
;	COMDAT ??_R2CGame@@8
; File d:\mycodes\chaosfighter\trunk\chaosfighter\hgegame\mygame.cpp
rdata$r	SEGMENT
??_R2CGame@@8 DD FLAT:??_R1A@?0A@EA@CGame@@8		; CGame::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CGame@@8
rdata$r	SEGMENT
??_R3CGame@@8 DD 00H					; CGame::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CGame@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCGame@@@8
_DATA	SEGMENT
??_R0?AVCGame@@@8 DD FLAT:??_7type_info@@6B@		; CGame `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCGame@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CGame@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CGame@@8 DD FLAT:??_R0?AVCGame@@@8	; CGame::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CGame@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CMyGame@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CMyGame@@8 DD FLAT:??_R0?AVCMyGame@@@8	; CMyGame::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CMyGame@@8
rdata$r	ENDS
;	COMDAT ??_R2CMyGame@@8
rdata$r	SEGMENT
??_R2CMyGame@@8 DD FLAT:??_R1A@?0A@EA@CMyGame@@8	; CMyGame::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CGame@@8
rdata$r	ENDS
;	COMDAT ??_R3CMyGame@@8
rdata$r	SEGMENT
??_R3CMyGame@@8 DD 00H					; CMyGame::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CMyGame@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCMyGame@@@8
_DATA	SEGMENT
??_R0?AVCMyGame@@@8 DD FLAT:??_7type_info@@6B@		; CMyGame `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCMyGame@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CMyGame@@6B@
rdata$r	SEGMENT
??_R4CMyGame@@6B@ DD 00H				; CMyGame::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCMyGame@@@8
	DD	FLAT:??_R3CMyGame@@8
rdata$r	ENDS
;	COMDAT ??_7CMyGame@@6B@
CONST	SEGMENT
??_7CMyGame@@6B@ DD FLAT:??_R4CMyGame@@6B@		; CMyGame::`vftable'
	DD	FLAT:?InitGame@CMyGame@@UAE_NXZ
	DD	FLAT:?FrameFunc@CMyGame@@UAEXM@Z
	DD	FLAT:?RenderFunc@CMyGame@@UAEXXZ
	DD	FLAT:?Release@CMyGame@@UAEXXZ
; Function compile flags: /Odtp /RTCsu /ZI
CONST	ENDS
;	COMDAT ??0CMyGame@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0CMyGame@@QAE@XZ PROC					; CMyGame::CMyGame, COMDAT
; _this$ = ecx
; Line 6
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CGame@@QAE@XZ			; CGame::CGame
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CMyGame@@6B@
; Line 7
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??0CMyGame@@QAE@XZ ENDP					; CMyGame::CMyGame
_TEXT	ENDS
PUBLIC	??1CMyGame@@QAE@XZ				; CMyGame::~CMyGame
EXTRN	??1CGame@@QAE@XZ:PROC				; CGame::~CGame
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??1CMyGame@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1CMyGame@@QAE@XZ PROC					; CMyGame::~CMyGame, COMDAT
; _this$ = ecx
; Line 11
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CMyGame@@6B@
; Line 12
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CGame@@QAE@XZ			; CGame::~CGame
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CMyGame@@QAE@XZ ENDP					; CMyGame::~CMyGame
_TEXT	ENDS
PUBLIC	??_C@_1BC@GECJJOJO@?$AAP?$AAA?$AAR?$AAT?$AAI?$AAC?$AAL?$AAE?$AA?$AA@ ; `string'
PUBLIC	??_C@_0CA@BFLMGGJK@Resource?1Particle?1particles?4png?$AA@ ; `string'
PUBLIC	??_C@_1O@LPGDINIK@?$AAA?$AAc?$AAt?$AAi?$AAo?$AAn?$AA?$AA@ ; `string'
PUBLIC	??_C@_0BM@LBNNLKEF@Resource?1Texture?1Action?4png?$AA@ ; `string'
PUBLIC	??_C@_15KGOJFLP@?$AAB?$AAG?$AA?$AA@		; `string'
PUBLIC	??_C@_0BI@LCJJCPEN@Resource?1Texture?1bg?4png?$AA@ ; `string'
EXTRN	??3@YAXPAX@Z:PROC				; operator delete
EXTRN	??0CMission@@QAE@PAVCGame@@@Z:PROC		; CMission::CMission
EXTRN	??0CMenuScreen@@QAE@PAVCGame@@@Z:PROC		; CMenuScreen::CMenuScreen
EXTRN	??2@YAPAXI@Z:PROC				; operator new
EXTRN	?LoadTexture@CResourceManager@@QAEXPB_WPBDK_N@Z:PROC ; CResourceManager::LoadTexture
EXTRN	?InitGame@CGame@@UAE_NXZ:PROC			; CGame::InitGame
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
;	COMDAT ??_C@_1BC@GECJJOJO@?$AAP?$AAA?$AAR?$AAT?$AAI?$AAC?$AAL?$AAE?$AA?$AA@
CONST	SEGMENT
??_C@_1BC@GECJJOJO@?$AAP?$AAA?$AAR?$AAT?$AAI?$AAC?$AAL?$AAE?$AA?$AA@ DB 'P'
	DB	00H, 'A', 00H, 'R', 00H, 'T', 00H, 'I', 00H, 'C', 00H, 'L', 00H
	DB	'E', 00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@BFLMGGJK@Resource?1Particle?1particles?4png?$AA@
CONST	SEGMENT
??_C@_0CA@BFLMGGJK@Resource?1Particle?1particles?4png?$AA@ DB 'Resource/P'
	DB	'article/particles.png', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1O@LPGDINIK@?$AAA?$AAc?$AAt?$AAi?$AAo?$AAn?$AA?$AA@
CONST	SEGMENT
??_C@_1O@LPGDINIK@?$AAA?$AAc?$AAt?$AAi?$AAo?$AAn?$AA?$AA@ DB 'A', 00H, 'c'
	DB	00H, 't', 00H, 'i', 00H, 'o', 00H, 'n', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@LBNNLKEF@Resource?1Texture?1Action?4png?$AA@
CONST	SEGMENT
??_C@_0BM@LBNNLKEF@Resource?1Texture?1Action?4png?$AA@ DB 'Resource/Textu'
	DB	're/Action.png', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_15KGOJFLP@?$AAB?$AAG?$AA?$AA@
CONST	SEGMENT
??_C@_15KGOJFLP@?$AAB?$AAG?$AA?$AA@ DB 'B', 00H, 'G', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@LCJJCPEN@Resource?1Texture?1bg?4png?$AA@
CONST	SEGMENT
??_C@_0BI@LCJJCPEN@Resource?1Texture?1bg?4png?$AA@ DB 'Resource/Texture/b'
	DB	'g.png', 00H					; `string'
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?InitGame@CMyGame@@UAE_NXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?InitGame@CMyGame@@UAE_NXZ$0
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?InitGame@CMyGame@@UAE_NXZ$1
__ehfuncinfo$?InitGame@CMyGame@@UAE_NXZ DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$?InitGame@CMyGame@@UAE_NXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu /ZI
xdata$x	ENDS
;	COMDAT ?InitGame@CMyGame@@UAE_NXZ
_TEXT	SEGMENT
tv167 = -268						; size = 4
tv150 = -268						; size = 4
$T105789 = -260						; size = 4
$T105790 = -248						; size = 4
$T105793 = -236						; size = 4
$T105794 = -224						; size = 4
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
?InitGame@CMyGame@@UAE_NXZ PROC				; CMyGame::InitGame, COMDAT
; _this$ = ecx
; Line 15
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?InitGame@CMyGame@@UAE_NXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-268]
	mov	ecx, 64					; 00000040H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
; Line 16
	mov	ecx, DWORD PTR _this$[ebp]
	call	?InitGame@CGame@@UAE_NXZ		; CGame::InitGame
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN1@InitGame
; Line 18
	xor	al, al
	jmp	$LN2@InitGame
$LN1@InitGame:
; Line 21
	push	0
	push	0
	push	OFFSET ??_C@_0BI@LCJJCPEN@Resource?1Texture?1bg?4png?$AA@
	push	OFFSET ??_C@_15KGOJFLP@?$AAB?$AAG?$AA?$AA@
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	call	?LoadTexture@CResourceManager@@QAEXPB_WPBDK_N@Z ; CResourceManager::LoadTexture
; Line 22
	push	0
	push	0
	push	OFFSET ??_C@_0BM@LBNNLKEF@Resource?1Texture?1Action?4png?$AA@
	push	OFFSET ??_C@_1O@LPGDINIK@?$AAA?$AAc?$AAt?$AAi?$AAo?$AAn?$AA?$AA@
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	call	?LoadTexture@CResourceManager@@QAEXPB_WPBDK_N@Z ; CResourceManager::LoadTexture
; Line 24
	push	0
	push	0
	push	OFFSET ??_C@_0CA@BFLMGGJK@Resource?1Particle?1particles?4png?$AA@
	push	OFFSET ??_C@_1BC@GECJJOJO@?$AAP?$AAA?$AAR?$AAT?$AAI?$AAC?$AAL?$AAE?$AA?$AA@
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	call	?LoadTexture@CResourceManager@@QAEXPB_WPBDK_N@Z ; CResourceManager::LoadTexture
; Line 26
	push	20					; 00000014H
	call	??2@YAPAXI@Z				; operator new
	add	esp, 4
	mov	DWORD PTR $T105790[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	cmp	DWORD PTR $T105790[ebp], 0
	je	SHORT $LN4@InitGame
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	mov	ecx, DWORD PTR $T105790[ebp]
	call	??0CMenuScreen@@QAE@PAVCGame@@@Z	; CMenuScreen::CMenuScreen
	mov	DWORD PTR tv150[ebp], eax
	jmp	SHORT $LN5@InitGame
$LN4@InitGame:
	mov	DWORD PTR tv150[ebp], 0
$LN5@InitGame:
	mov	ecx, DWORD PTR tv150[ebp]
	mov	DWORD PTR $T105789[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR $T105789[ebp]
	mov	DWORD PTR [edx+52], eax
; Line 27
	push	24					; 00000018H
	call	??2@YAPAXI@Z				; operator new
	add	esp, 4
	mov	DWORD PTR $T105794[ebp], eax
	mov	DWORD PTR __$EHRec$[ebp+8], 1
	cmp	DWORD PTR $T105794[ebp], 0
	je	SHORT $LN6@InitGame
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	mov	ecx, DWORD PTR $T105794[ebp]
	call	??0CMission@@QAE@PAVCGame@@@Z		; CMission::CMission
	mov	DWORD PTR tv167[ebp], eax
	jmp	SHORT $LN7@InitGame
$LN6@InitGame:
	mov	DWORD PTR tv167[ebp], 0
$LN7@InitGame:
	mov	ecx, DWORD PTR tv167[ebp]
	mov	DWORD PTR $T105793[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR $T105793[ebp]
	mov	DWORD PTR [edx+56], eax
; Line 29
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	edx, DWORD PTR [ecx+56]
	mov	DWORD PTR [eax+12], edx
; Line 31
	mov	al, 1
$LN2@InitGame:
; Line 32
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 268				; 0000010cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?InitGame@CMyGame@@UAE_NXZ$0:
	mov	eax, DWORD PTR $T105790[ebp]
	push	eax
	call	??3@YAXPAX@Z				; operator delete
	pop	ecx
	ret	0
__unwindfunclet$?InitGame@CMyGame@@UAE_NXZ$1:
	mov	eax, DWORD PTR $T105794[ebp]
	push	eax
	call	??3@YAXPAX@Z				; operator delete
	pop	ecx
	ret	0
__ehhandler$?InitGame@CMyGame@@UAE_NXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-272]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?InitGame@CMyGame@@UAE_NXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?InitGame@CMyGame@@UAE_NXZ ENDP				; CMyGame::InitGame
EXTRN	?FrameFunc@CGame@@UAEXM@Z:PROC			; CGame::FrameFunc
EXTRN	__fltused:DWORD
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?FrameFunc@CMyGame@@UAEXM@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_fDeltaTime$ = 8					; size = 4
?FrameFunc@CMyGame@@UAEXM@Z PROC			; CMyGame::FrameFunc, COMDAT
; _this$ = ecx
; Line 35
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 36
	push	ecx
	fld	DWORD PTR _fDeltaTime$[ebp]
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?FrameFunc@CGame@@UAEXM@Z		; CGame::FrameFunc
; Line 37
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?FrameFunc@CMyGame@@UAEXM@Z ENDP			; CMyGame::FrameFunc
_TEXT	ENDS
EXTRN	?RenderFunc@CGame@@UAEXXZ:PROC			; CGame::RenderFunc
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?RenderFunc@CMyGame@@UAEXXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?RenderFunc@CMyGame@@UAEXXZ PROC			; CMyGame::RenderFunc, COMDAT
; _this$ = ecx
; Line 40
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 41
	mov	ecx, DWORD PTR _this$[ebp]
	call	?RenderFunc@CGame@@UAEXXZ		; CGame::RenderFunc
; Line 42
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?RenderFunc@CMyGame@@UAEXXZ ENDP			; CMyGame::RenderFunc
_TEXT	ENDS
EXTRN	?Release@CGame@@UAEXXZ:PROC			; CGame::Release
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?Release@CMyGame@@UAEXXZ
_TEXT	SEGMENT
tv89 = -256						; size = 4
tv78 = -256						; size = 4
$T105817 = -248						; size = 4
$T105818 = -236						; size = 4
$T105821 = -224						; size = 4
$T105822 = -212						; size = 4
_this$ = -8						; size = 4
?Release@CMyGame@@UAEXXZ PROC				; CMyGame::Release, COMDAT
; _this$ = ecx
; Line 45
	push	ebp
	mov	ebp, esp
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-256]
	mov	ecx, 64					; 00000040H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 46
	mov	ecx, DWORD PTR _this$[ebp]
	call	?Release@CGame@@UAEXXZ			; CGame::Release
; Line 47
	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+52], 0
	je	SHORT $LN2@Release
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+52]
	mov	DWORD PTR $T105818[ebp], ecx
	mov	edx, DWORD PTR $T105818[ebp]
	mov	DWORD PTR $T105817[ebp], edx
	cmp	DWORD PTR $T105817[ebp], 0
	je	SHORT $LN5@Release
	mov	esi, esp
	push	1
	mov	eax, DWORD PTR $T105817[ebp]
	mov	edx, DWORD PTR [eax]
	mov	ecx, DWORD PTR $T105817[ebp]
	mov	eax, DWORD PTR [edx]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv78[ebp], eax
	jmp	SHORT $LN2@Release
$LN5@Release:
	mov	DWORD PTR tv78[ebp], 0
$LN2@Release:
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+52], 0
; Line 48
	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+56], 0
	je	SHORT $LN1@Release
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+56]
	mov	DWORD PTR $T105822[ebp], ecx
	mov	edx, DWORD PTR $T105822[ebp]
	mov	DWORD PTR $T105821[ebp], edx
	cmp	DWORD PTR $T105821[ebp], 0
	je	SHORT $LN7@Release
	mov	esi, esp
	push	1
	mov	eax, DWORD PTR $T105821[ebp]
	mov	edx, DWORD PTR [eax]
	mov	ecx, DWORD PTR $T105821[ebp]
	mov	eax, DWORD PTR [edx]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv89[ebp], eax
	jmp	SHORT $LN1@Release
$LN7@Release:
	mov	DWORD PTR tv89[ebp], 0
$LN1@Release:
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+56], 0
; Line 49
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 256				; 00000100H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?Release@CMyGame@@UAEXXZ ENDP				; CMyGame::Release
_TEXT	ENDS
END
